// frontend/src/components/Navbar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { Bars3Icon, XMarkIcon, MagnifyingGlassIcon, ChevronDownIcon, SunIcon, MoonIcon } from '@heroicons/vue/24/outline'
import { isDarkMode, toggleDarkMode } from '../utils/darkMode'

const router = useRouter()
const isMenuOpen = ref(false)
const searchQuery = ref('')

const navigation = [
  { name: 'Home', href: '/' },
  { 
    name: 'About', 
    href: '/about',
    dropdown: [
      { name: 'Who We Are', href: '/about' },
      { name: 'Vision & Purpose', href: '/about#vision' },
      { name: 'Board of Directors', href: '/about/leadership#board' },
      { name: 'Executive Management', href: '/about/leadership#executive' },
      { name: 'Functional Heads', href: '/about/leadership#functional' },
      { name: 'Donor Agencies', href: '/about/partners#donor' },
      { name: 'Financial Institutions', href: '/about/partners#financial' },
      { name: 'Government Agencies', href: '/about/partners#government' },
      { name: 'Non-Governmental Organizations', href: '/about/partners#ngo' },
      { name: 'Private Agencies', href: '/about/partners#private' },
      { name: 'Procurement Opportunities', href: '/about/partners#tenders' }
    ]
  },
  { 
    name: 'Services', 
    href: '/services',
    dropdown: [
      { name: 'Trading Platform', href: '/services/trading' },
      { name: 'Market Data', href: '/services/data' },
      { name: 'Clearing & Settlement', href: '/services/clearing' },
      { name: 'Risk Management', href: '/services/risk' }
    ]
  },
  { 
    name: 'Membership', 
    href: '/membership',
    dropdown: [
      { name: 'Become a Member', href: '/membership/apply' },
      { name: 'Member Types', href: '/membership/types' },
      { name: 'Benefits', href: '/membership/benefits' },
      { name: 'Rules & Regulations', href: '/membership/rules' }
    ]
  },
  { 
    name: 'Market Data', 
    href: '/market-data',
    dropdown: [
      { name: 'Live Prices', href: '/market-data/prices' },
      { name: 'Market Reports', href: '/market-data/reports' },
      { name: 'Trading Statistics', href: '/market-data/stats' }
    ]
  },
  { name: 'Contact', href: '/contact' },
]

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

const closeMenu = () => {
  isMenuOpen.value = false
}

const handleSearch = () => {
  if (searchQuery.value.trim()) {
    alert(`Searching for: ${searchQuery.value}`)
    searchQuery.value = ''
  }
}

// Dropdown state
const openDropdown = ref<string | null>(null)

const toggleDropdown = (itemName: string) => {
  openDropdown.value = openDropdown.value === itemName ? null : itemName
}

const closeDropdown = () => {
  openDropdown.value = null
}
</script>

<template>
    <!-- Modern Glassmorphism Navbar -->
  <nav class="fixed top-0 left-0 right-0 z-40 backdrop-blur-md transition-colors duration-300" :class="isDarkMode ? 'bg-slate-900/90' : 'bg-white/90'">
    <!-- Main navbar content -->
    <div class="w-full px-6">
      <div class="flex justify-between items-center h-20">
        <!-- Logo - Far left edge -->
        <div class="flex-shrink-0">
          <router-link to="/" class="flex items-center group">
            <img src="/logo_black.png" alt="GCX Logo" class="h-20 w-auto transition-transform group-hover:scale-105" />
          </router-link>
        </div>

        <!-- Desktop Navigation - Centered with more spacing -->
        <div class="hidden lg:flex items-center flex-1 justify-center">
          <div class="flex items-center space-x-4 rounded-full p-3 transition-colors duration-300" :class="isDarkMode ? 'bg-slate-800/80' : 'bg-slate-100/80'">
            <div
              v-for="item in navigation"
              :key="item.name"
              class="relative"
              @mouseenter="item.dropdown ? toggleDropdown(item.name) : null"
              @mouseleave="closeDropdown"
            >
              <router-link
                :to="item.href"
                class="px-6 py-3 text-sm font-medium rounded-full transition-all flex items-center"
                                 :class="$route.path === item.href 
                   ? (isDarkMode ? 'bg-slate-700 text-white' : 'bg-white shadow-sm text-slate-900')
                   : (isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-600 hover:text-slate-900')"
              >
                {{ item.name }}
                <ChevronDownIcon v-if="item.dropdown" class="w-4 h-4 ml-1" />
              </router-link>
              
              <!-- Dropdown Menu -->
              <div
                v-if="item.dropdown && openDropdown === item.name"
                class="absolute top-full left-0 mt-2 w-80 rounded-xl shadow-xl border py-2 z-50 transition-colors duration-300 max-h-96 overflow-y-auto"
                :class="isDarkMode ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-200'"
              >
                <!-- Group 1: Who We Are -->
                <div class="px-4 py-2">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Organization</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(0, 2)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-700 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
                
                <!-- Group 2: Leadership -->
                <div class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Leadership</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(2, 5)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-700 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
                
                <!-- Group 3: Partners -->
                <div class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Partners</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(5, 10)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-700 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
                
                <!-- Group 4: Opportunities -->
                <div class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Opportunities</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(10)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-700 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Right side -->
        <div class="flex items-center space-x-4">
          <!-- Search -->
          <div class="hidden lg:flex items-center">
            <div class="relative">
              <MagnifyingGlassIcon class="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-slate-400" />
              <input
                v-model="searchQuery"
                @keyup.enter="handleSearch"
                type="text"
                placeholder="Search markets..."
                class="w-64 pl-9 pr-4 py-2.5 text-sm border-0 rounded-full focus:outline-none focus:ring-2 focus:ring-yellow-400 transition-all"
                :class="isDarkMode ? 'bg-slate-800/80 text-white placeholder-slate-400 focus:bg-slate-700' : 'bg-slate-100/80 text-slate-900 placeholder-slate-500 focus:bg-white'"
              />
            </div>
          </div>

          <!-- Dark Mode Toggle -->
          <div class="hidden lg:flex items-center">
            <button
              @click="toggleDarkMode"
              class="p-2 rounded-full transition-colors"
              :class="isDarkMode ? 'bg-slate-700 hover:bg-slate-600' : 'bg-slate-100 hover:bg-slate-200'"
            >
              <SunIcon v-if="!isDarkMode" class="h-5 w-5 text-slate-600" />
              <MoonIcon v-else class="h-5 w-5 text-slate-300" />
            </button>
          </div>

          <!-- Get Started Button Only -->
          <div class="hidden lg:flex items-center">
            <button class="bg-gradient-to-r from-yellow-500 to-yellow-600 hover:from-yellow-600 hover:to-yellow-700 text-black font-semibold px-8 py-2.5 rounded-full transition-all transform hover:scale-105 shadow-lg hover:shadow-xl">
              Get Started
            </button>
          </div>

          <!-- Mobile menu button -->
          <div class="lg:hidden">
                         <button
               @click="toggleMenu"
               class="p-2 rounded-full transition-colors"
               :class="isDarkMode ? 'bg-slate-700 hover:bg-slate-600' : 'bg-slate-100 hover:bg-slate-200'"
             >
              <Bars3Icon v-if="!isMenuOpen" class="h-5 w-5 text-slate-600" />
              <XMarkIcon v-else class="h-5 w-5 text-slate-600" />
            </button>
          </div>
        </div>
      </div>

      <!-- Mobile menu -->
      <div v-show="isMenuOpen" class="lg:hidden">
                 <div class="py-4 space-y-2 backdrop-blur-md rounded-2xl mx-4 mb-4 shadow-xl border transition-colors duration-300" :class="isDarkMode ? 'bg-slate-800/95 border-slate-700/50' : 'bg-white/95 border-slate-200/50'">
          <!-- Mobile Search -->
          <div class="px-4 mb-4">
            <div class="relative">
              <MagnifyingGlassIcon class="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-slate-400" />
              <input
                v-model="searchQuery"
                @keyup.enter="handleSearch"
                type="text"
                placeholder="Search markets..."
                                 class="w-full pl-9 pr-4 py-2 text-sm border-0 rounded-full focus:outline-none focus:ring-2 focus:ring-yellow-400 transition-colors"
                 :class="isDarkMode ? 'bg-slate-700 text-white placeholder-slate-400' : 'bg-slate-100 text-slate-900 placeholder-slate-500'"
              />
            </div>
          </div>

          <!-- Mobile Navigation -->
          <div class="px-2">
            <div v-for="item in navigation" :key="item.name">
              <router-link
                :to="item.href"
                @click="closeMenu"
                class="block px-4 py-3 text-base font-medium rounded-xl transition-colors"
                :class="$route.path === item.href 
                  ? (isDarkMode ? 'bg-slate-700 text-white' : 'bg-slate-100 text-slate-900')
                  : (isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900')"
              >
                {{ item.name }}
              </router-link>
              
              <!-- Mobile About Dropdown -->
              <div v-if="item.dropdown" class="mt-2 ml-4 space-y-1">
                <div class="px-4 py-2">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Organization</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(0, 2)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    @click="closeMenu"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
                
                <div class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Leadership</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(2, 5)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    @click="closeMenu"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
                
                <div class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Partners</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(5, 10)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    @click="closeMenu"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
                
                <div class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
                  <h4 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">Opportunities</h4>
                  <router-link
                    v-for="dropdownItem in item.dropdown.slice(10)"
                    :key="dropdownItem.name"
                    :to="dropdownItem.href"
                    @click="closeMenu"
                    class="block px-2 py-2 text-sm transition-colors rounded-lg"
                    :class="isDarkMode ? 'text-slate-300 hover:bg-slate-700 hover:text-white' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'"
                  >
                    {{ dropdownItem.name }}
                  </router-link>
                </div>
              </div>
            </div>
          </div>

          <!-- Mobile Buttons -->
          <div class="px-4 pt-4">
            <button class="w-full bg-gradient-to-r from-yellow-500 to-yellow-600 hover:from-yellow-600 hover:to-yellow-700 text-black font-semibold py-3 px-6 rounded-full transition-all">
              Get Started
            </button>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Gold Line at Bottom - Full Width -->
    <div class="h-1 bg-gradient-to-r from-yellow-400 to-yellow-600 w-full"></div>
  </nav>

  <!-- Spacer for fixed navbar -->
  <div class="h-20"></div>
</template>

// gcx_marketdata/src/components/layout/Navbar.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { Menu, X, User, LogOut, Bell, Search, Crown, BarChart3 } from 'lucide-react';
import { useSession, signOut } from 'next-auth/react';
import { SimpleThemeToggle } from '@/components/ui/ThemeToggle';

export default function Navbar() {
  const { data: session } = useSession();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchFocused, setSearchFocused] = useState(false);

  const handleLogout = async () => {
    await signOut({ redirect: true, callbackUrl: '/' });
  };

  return (
    <nav className="text-card-foreground shadow-lg border-b border-border sticky top-0 z-50 backdrop-blur-sm bg-card/95 transition-colors duration-300">
      <div className="w-full px-6 lg:px-8">
        <div className="flex justify-between items-center h-20">
          {/* Logo Section - Left */}
          <div className="flex items-center flex-shrink-0">
            <Link href="/" className="flex items-center space-x-4 group">
              <div className="w-12 h-12 bg-gradient-to-br from-green-600 via-green-700 to-green-800 dark:from-green-500 dark:via-green-600 dark:to-green-700 rounded-2xl flex items-center justify-center shadow-lg group-hover:shadow-xl transition-all duration-300 transform group-hover:scale-105">
                <Image
                  src="/logo_black.png"
                  alt="GCX Logo"
                  width={28}
                  height={28}
                  className="object-contain filter brightness-0 invert"
                  priority
                />
              </div>
              <div className="hidden sm:block">
                <h1 className="text-2xl font-bold text-card-foreground">
                  GCX Market Data
                </h1>
                <p className="text-xs text-muted-foreground font-medium">Professional Trading Platform</p>
              </div>
            </Link>
          </div>

          {/* Search Bar - Center (Full Width) */}
          <div className="flex-1 flex justify-center px-8 lg:px-16">
            <div className="relative group w-full max-w-2xl">
              <Search className={`absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 transition-colors duration-200 ${
                searchFocused ? 'text-primary' : 'text-muted-foreground'
              }`} />
              <input
                type="text"
                placeholder="Search commodities, markets, news, or analysis..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onFocus={() => setSearchFocused(true)}
                onBlur={() => setSearchFocused(false)}
                className="w-full pl-12 pr-6 py-3.5 text-sm border-2 border-border rounded-2xl focus:ring-4 focus:ring-primary/20 focus:border-primary transition-all duration-300 bg-card text-card-foreground placeholder-muted-foreground shadow-sm focus:shadow-lg"
              />
              {searchQuery && (
                <button 
                  onClick={() => setSearchQuery('')}
                  className="absolute right-4 top-1/2 transform -translate-y-1/2 p-1 text-muted-foreground hover:text-card-foreground rounded-full hover:bg-muted transition-all duration-200"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
            </div>
          </div>

          {/* Right Side Actions - Bell & Profile */}
          <div className="flex items-center space-x-4 flex-shrink-0">
            {/* Theme Toggle */}
            <SimpleThemeToggle />
            
            {/* Enhanced Notifications - Only show when authenticated */}
            {session && (
              <button className="relative p-3 text-muted-foreground hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-all duration-200 group">
                <Bell className="w-5 h-5 group-hover:scale-110 transition-transform duration-200" />
                <span className="absolute top-2 right-2 block h-3 w-3 rounded-full bg-red-500 ring-2 ring-card animate-pulse"></span>
                <span className="absolute -top-1 -right-1 block h-5 w-5 rounded-full bg-red-100 dark:bg-red-900/20 opacity-0 group-hover:opacity-100 transition-opacity duration-200"></span>
              </button>
            )}
            
            {/* Enhanced User Profile */}
            {session ? (
              <div className="relative">
                <button
                  onClick={() => setUserMenuOpen(!userMenuOpen)}
                  className="flex items-center space-x-3 p-2 rounded-xl hover:bg-muted transition-all duration-200 group"
                >
                  <div className="w-10 h-10 bg-gradient-to-br from-green-600 to-green-700 dark:from-green-500 dark:to-green-600 rounded-full flex items-center justify-center shadow-md group-hover:shadow-lg transition-all duration-200">
                    <User className="w-5 h-5 text-white" />
                  </div>
                  <div className="hidden sm:block text-left">
                    <span className="text-sm font-semibold text-card-foreground block">{session.user?.name || 'User'}</span>
                    <div className="flex items-center space-x-1">
                      <Crown className="w-3 h-3 text-yellow-500 dark:text-yellow-400" />
                      <span className="text-xs text-muted-foreground font-medium">Premium</span>
                    </div>
                  </div>
                </button>
                
                {/* Enhanced User Dropdown Menu */}
                {userMenuOpen && (
                  <div className="absolute right-0 mt-3 w-64 bg-card text-card-foreground rounded-2xl shadow-2xl border border-border py-3 z-50">
                    {/* User Header */}
                    <div className="px-6 py-4 border-b border-border bg-muted/50 rounded-t-2xl">
                      <div className="flex items-center space-x-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-green-600 to-green-700 rounded-full flex items-center justify-center shadow-md">
                          <User className="w-6 h-6 text-white" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-card-foreground truncate">{session.user?.name || 'User'}</p>
                          <div className="flex items-center space-x-2 mt-1">
                            <Crown className="w-3 h-3 text-yellow-500" />
                            <p className="text-xs text-muted-foreground font-medium">Premium Member</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    {/* Quick Stats */}
                    <div className="px-6 py-3 border-b border-border">
                      <div className="grid grid-cols-2 gap-3">
                        <div className="text-center p-2 bg-green-50 dark:bg-green-900/20 rounded-lg">
                          <p className="text-xs text-muted-foreground">Portfolio</p>
                          <p className="text-sm font-semibold text-green-600 dark:text-green-400">₵45.2M</p>
                        </div>
                        <div className="text-center p-2 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg">
                          <p className="text-xs text-muted-foreground">Today's P&L</p>
                          <p className="text-sm font-semibold text-yellow-600 dark:text-yellow-400">+₵2.1M</p>
                        </div>
                      </div>
                    </div>
                    
                    {/* Menu Items */}
                    <div className="py-2">
                      <Link
                        href="/profile"
                        className="flex items-center space-x-3 px-6 py-3 text-sm text-muted-foreground hover:bg-muted hover:text-card-foreground transition-all duration-200"
                        onClick={() => setUserMenuOpen(false)}
                      >
                        <User className="w-4 h-4" />
                        <span>Profile & Settings</span>
                      </Link>
                      <Link
                        href="/portfolio"
                        className="flex items-center space-x-3 px-6 py-3 text-sm text-muted-foreground hover:bg-muted hover:text-card-foreground transition-all duration-200"
                        onClick={() => setUserMenuOpen(false)}
                      >
                        <BarChart3 className="w-4 h-4" />
                        <span>Portfolio</span>
                      </Link>
                      <Link
                        href="/alerts"
                        className="flex items-center space-x-3 px-6 py-3 text-sm text-muted-foreground hover:bg-muted hover:text-card-foreground transition-all duration-200"
                        onClick={() => setUserMenuOpen(false)}
                      >
                        <Bell className="w-4 h-4" />
                        <span>Alerts & Notifications</span>
                      </Link>
                    </div>
                    
                    {/* Footer Actions */}
                    <div className="border-t border-border pt-2 px-6 pb-3">
                      <button 
                        onClick={() => {
                          handleLogout();
                          setUserMenuOpen(false);
                        }}
                        className="w-full flex items-center justify-center space-x-2 px-4 py-2.5 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-700 dark:hover:text-red-300 rounded-xl transition-all duration-200 border border-red-200 dark:border-red-700 hover:border-red-300 dark:hover:border-red-600"
                      >
                        <LogOut className="w-4 h-4" />
                        <span>Sign Out</span>
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex items-center space-x-3">
                <Link
                  href="/auth/login"
                  className="text-muted-foreground hover:text-card-foreground px-4 py-2.5 text-sm font-medium transition-all duration-200 hover:bg-muted rounded-xl"
                >
                  Sign In
                </Link>
                <Link
                  href="/auth/register"
                  className="bg-gradient-to-r from-green-600 to-green-700 text-white px-6 py-2.5 rounded-xl text-sm font-semibold hover:from-green-700 hover:to-green-800 transition-all duration-200 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
                >
                  Get Started
                </Link>
              </div>
            )}

            {/* Mobile menu button */}
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="lg:hidden p-2 text-muted-foreground hover:text-card-foreground hover:bg-muted rounded-xl transition-all duration-200"
            >
              {mobileMenuOpen ? (
                <X className="w-6 h-6" />
              ) : (
                <Menu className="w-6 h-6" />
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Enhanced Mobile Search and Menu */}
      {mobileMenuOpen && (
        <div className="lg:hidden border-t border-border bg-card text-card-foreground px-4 py-6 shadow-lg">
          {/* Mobile Search */}
          <div className="relative mb-6">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <input
              type="text"
              placeholder="Search commodities, markets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-12 pr-4 py-3.5 text-sm border-2 border-border rounded-2xl focus:ring-4 focus:ring-primary/20 focus:border-primary transition-all duration-200 bg-card text-card-foreground placeholder-muted-foreground"
            />
          </div>
          
          {/* Mobile Menu Items */}
          {session ? (
            <div className="space-y-3">
              <Link
                href="/profile"
                className="flex items-center space-x-3 px-4 py-3 text-muted-foreground hover:text-card-foreground hover:bg-muted rounded-xl transition-all duration-200"
                onClick={() => setMobileMenuOpen(false)}
              >
                <User className="w-5 h-5" />
                <span>Profile & Settings</span>
              </Link>
              <Link
                href="/portfolio"
                className="flex items-center space-x-3 px-4 py-3 text-muted-foreground hover:text-card-foreground hover:bg-muted rounded-xl transition-all duration-200"
                onClick={() => setMobileMenuOpen(false)}
              >
                <BarChart3 className="w-5 h-5" />
                <span>Portfolio</span>
              </Link>
              <Link
                href="/alerts"
                className="flex items-center space-x-3 px-4 py-3 text-muted-foreground hover:text-card-foreground hover:bg-muted rounded-xl transition-all duration-200"
                onClick={() => setMobileMenuOpen(false)}
              >
                <Bell className="w-5 h-5" />
                <span>Alerts & Notifications</span>
              </Link>
              <button 
                onClick={() => {
                  handleLogout();
                  setMobileMenuOpen(false);
                }}
                className="w-full flex items-center space-x-3 px-4 py-3 text-red-600 dark:text-red-400 hover:text-red-700 dark:hover:text-red-300 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-all duration-200"
              >
                <LogOut className="w-5 h-5" />
                <span>Sign Out</span>
              </button>
            </div>
          ) : (
            <div className="space-y-3">
              <Link
                href="/auth/login"
                className="flex items-center justify-center px-4 py-3 text-muted-foreground hover:text-card-foreground hover:bg-muted rounded-xl transition-all duration-200 border border-border"
                onClick={() => setMobileMenuOpen(false)}
              >
                Sign In
              </Link>
              <Link
                href="/auth/register"
                className="flex items-center justify-center px-4 py-3 bg-gradient-to-r from-green-600 to-green-700 text-white rounded-xl hover:from-green-700 hover:to-green-800 transition-all duration-200 shadow-lg"
                onClick={() => setMobileMenuOpen(false)}
              >
                Get Started
              </Link>
            </div>
          )}
        </div>
      )}
    </nav>
  );
}
